### ISSUE TITLE
How to initiate the configuration file

### ISSUE THREAD

**Issue by panday1995** [JGCRI/pygcam#18]
Hi. I am trying to install `pygcam`. I've downloaded gcam v4.4, pip installed `pygcam` in a python3 virtual environment. But I don't understand how to conduct `init` command to intialize the configuration file ~/.pygcam.cfg

I tried 
```
import pygcam
pygcam.__init__()
```
but didn't work

**Comment by panday1995** [comment]
I just checked the `__init__` file in pygcam and found it's empty. Should I insert some codes to initialize it?

**Comment by panday1995** [comment]
When I am using `gt init` in pygcam environment, anaconda prompt,  it raised
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/sheep/.pygcam.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\sheep\Anaconda3\envs\pygcam\Scripts\gt.exe\__main__.py", line 4, in <module>
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\tool.py", line 17, in <module>
    from .built_ins import BuiltinSubcommands
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\built_ins\__init__.py", line 1, in <module>
    from .building_plugin import BuildingCommand
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\built_ins\building_plugin.py", line 13, in <module>
    _logger = getLogger(__name__)
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\log.py", line 56, in getLogger
    _configureLogger(name)
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\log.py", line 135, in _configureLogger
    setLogLevels(getParam('GCAM.LogLevel') or 'WARN')
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\config.py", line 477, in getParam
    getConfig()
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\config.py", line 189, in getConfig
    return _ConfigParser or readConfigFiles(allowMissing=allowMissing)
  File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\config.py", line 388, in readConfigFiles
    raise ConfigFileError("Missing configuration file %s" % usrConfigPath)
pygcam.error.ConfigFileError: Missing configuration file C:/Users/sheep/.pygcam.cfg
```

**Comment by panday1995** [comment]
> When I am using `gt init` in pygcam environment, anaconda prompt, it raised
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/sheep/.pygcam.cfg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "D:\Users\sheep\Anaconda3\envs\pygcam\Scripts\gt.exe\__main__.py", line 4, in <module>
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\tool.py", line 17, in <module>
>     from .built_ins import BuiltinSubcommands
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\built_ins\__init__.py", line 1, in <module>
>     from .building_plugin import BuildingCommand
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\built_ins\building_plugin.py", line 13, in <module>
>     _logger = getLogger(__name__)
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\log.py", line 56, in getLogger
>     _configureLogger(name)
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\log.py", line 135, in _configureLogger
>     setLogLevels(getParam('GCAM.LogLevel') or 'WARN')
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\config.py", line 477, in getParam
>     getConfig()
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\config.py", line 189, in getConfig
>     return _ConfigParser or readConfigFiles(allowMissing=allowMissing)
>   File "d:\users\sheep\anaconda3\envs\pygcam\lib\site-packages\pygcam\config.py", line 388, in readConfigFiles
>     raise ConfigFileError("Missing configuration file %s" % usrConfigPath)
> pygcam.error.ConfigFileError: Missing configuration file C:/Users/sheep/.pygcam.cfg
> ```

Here I'm a litter confused. The doc says `init` command would generate the `.pygcam.cfg` configuration file. But the `gt init` command requires the presence of the `.pygcam.cfg` file. Should I go to the `config.py` file to insert somewhere in the code the place I installed gcam_v4.4?

**Comment by panday1995** [comment]
Hi @rjplevin, I downgraded `pygcam 1.9` to `pygcam 1.8`, and anyhow, it works. I think there maybe some bugs with configurition in `pygcam 1.9` (missing the `pygcam.cfg` or something related). Because when debugging `pygcam 1.9`, I search through all pygcam related files but didn't find one.
