### ISSUE TITLE
basex->csv

### ISSUE THREAD

**Issue by huanglin6385** [JGCRI/pygcam#23]
Hello:
I want to process the output, the output basex folder is 'output/database_basexdb/'
the query is 'input/queries.xml'

the code is like follow:
```
from pygcam.query import *

r = runBatchQuery(scenario='111', queryName='queries', queryPath='input/', outputDir='tf_test/', xmldb='output/database_basexdb/') 

```

the exception is like follow:

> WARNING pygcam.query: runModelInterface called with both batchFile and csvFile; the latter is ignored.
> InterfaceMain: batchFile: queries-111.csv
> Running headless? true
> java.lang.NullPointerException
>         at ModelInterface.ConfigurationEditor.utils.FileUtils.loadDocument(FileUtils.java:301)
>         at ModelInterface.InterfaceMain.main(InterfaceMain.java:192)

As i am a new bird in pygcam, i can not find the tutorial of using 'queries.xml' to query in basex.
Looking forward to your reply!
Best wishes!

**Comment by rjplevin** [comment]
Please post the contents of your queries.xml file. You're using a function that runs only a single query and is no longer used by the command-line tool (`gt`), since the general case of running multiple queries handles 1 query, too. But I can make sure it's still working again. If queries.xml file contains multiple queries, you should use this instead:
```
def runMultiQueryBatch(scenario, queries, xmldb='', queryPath=None, outputDir=None,
                       miLogFile=None, regions=None, regionMap=None, rewriteParser=None,
                       batchFileIn=None, batchFileOut=None, noRun=False, noDelete=False):
    """
    Create a single GCAM XML batch file that runs multiple queries, placing the
    each query's results in a file named of the form {queryName}-{scenario}.csv.

    :param scenario: (str) the name of the scenario to perform the query on
    :param queries: (list of str query names and/or Query instances)
    :param xmldb: (str) path to XMLDB, or '' to use in-memory DB
    :param queryPath: (str) a list of directories or XML filenames, separated
        by a colon (on Unix) or a semi-colon (on Windows)
    :param outputDir: (str) the directory in which to write the .CSV
        with query results, default is value of GCAM.OutputDir.
    :param regions: (iterable of str) the regions you want to include in the query
    :param regionMap: (dict-like) keys are the names of regions that should be rewritten.
        The value is the name of the aggregate region to map into.
    :param rewriteParser: (RewriteSetParser instance) parsed representation of
        rewriteSets.xml
    :param batchFileIn: (str) the name of a pre-formed batch file to run
    :param batchFileOut: (str) where to write output from batchFileIn, if given
    :param noRun: (bool) if True, print the command that would be executed, but
        don't run it.
    :param noDelete: (bool) if True, temporary files created by this function are
        not deleted (use for debugging)
    :return: none
    """
```

**Comment by rjplevin** [comment]
I've pushed the bug fix in version 10.0.1 to git and the pip server. Thanks for reporting the error!

Note that your `.pygcam.cfg` file will need to be correct since some parameter values are taken from there. Contact me by email if you want to follow up. (rich@plevin.com).

**Comment by rjplevin** [comment]
FWIW, here's my test program. This script must be run from the `exe` directory since it uses a relative path to the output directory.
```

from pygcam.query import runBatchQuery

runBatchQuery(scenario='base',
              queryName='oil_supply',
              queryPath='/tmp/elasticity_queries.xml',
              outputDir='/tmp',
              xmldb='../output/database_basexdb')

```
Here are the contents of elasticity_queries.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<queries>
	<queryGroup name="markets and prices">
		<marketQuery title="oil price">
			<axis1 name="market">market</axis1>
			<axis2 name="Year">market</axis2>
			<xPath buildList="true" dataName="price" group="false" sumAll="false">Marketplace/market[true() and contains(@name,'crude oil')]/price/node()</xPath>
		</marketQuery>

		<marketQuery title="oil supply">
				<axis1 name="market">market</axis1>
				<axis2 name="Year">market</axis2>
				<xPath buildList="true" dataName="supply" group="false" sumAll="false">Marketplace/market[true() and contains(@name, 'crude oil')]/supply/node()</xPath>
		 </marketQuery>

		<marketQuery title="USA_ethanol_price">
			<axis1 name="market">market</axis1>
			<axis2 name="Year">market</axis2>
			<xPath buildList="true" dataName="price" group="false" sumAll="false">Marketplace/market[true() and @name='USAethanol']/price/node()</xPath>
		</marketQuery>
		
		<marketQuery title="corn_price">
			<axis1 name="market">market</axis1>
			<axis2 name="Year">market</axis2>
			<xPath buildList="true" dataName="price" group="false" sumAll="false">Marketplace/market[true() and ends-with(@name,'regional corn')]/price/node()</xPath>
		</marketQuery>
		
		<marketQuery title="oilcrop_price">
			<axis1 name="market">market</axis1>
			<axis2 name="Year">market</axis2>
			<xPath buildList="true" dataName="price" group="false" sumAll="false">Marketplace/market[true() and ends-with(@name,'regional oilcrop')]/price/node()</xPath>
		</marketQuery>

	</queryGroup>
</queries>
```

**Comment by huanglin6385** [comment]
```
>>> from pygcam.query import runBatchQuery


runBatchQuery(scenario='base',
              queryName='Primary Energy Consumption (Average Fossil Efficiency Conversion)',
              queryPath='//home/gcam/gcam-v4.4/output/queries/Main_queries.xml',
              outputDir='/home/gcam/gcam-v4.4/output',
              xmldb='/home/gcam/gcam-v4.4/output/database_basexdb')
>>>
>>>
>>>
>>> runBatchQuery(scenario='base',
...               queryName='Primary Energy Consumption (Average Fossil Efficiency Conversion)',
...               queryPath='//home/gcam/gcam-v4.4/output/queries/Main_queries.xml',
...               outputDir='/home/gcam/gcam-v4.4/output',
...               xmldb='/home/gcam/gcam-v4.4/output/database_basexdb')
InterfaceMain: batchFile: /tmp/tmpQ_FEbp.batch.xml
Running headless? true
ERROR; java.lang.NoClassDefFoundError: org/basex/core/Proc
java.lang.NoClassDefFoundError: org/basex/core/Proc
        at ModelInterface.ModelGUI2.DbViewer.runBatch(DbViewer.java:1853)
        at ModelInterface.InterfaceMain.runBatch(InterfaceMain.java:650)
        at ModelInterface.InterfaceMain.main(InterfaceMain.java:206)
Caused by: java.lang.ClassNotFoundException: org.basex.core.Proc
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
ERROR pygcam.query: Batch file '/tmp/tmp4nuxun.query.xml' failed. Deleting '/home/gcam/gcam-v4.4/output/Primary_Energy_Consumption_(Average_Fossil_Efficiency_Conversion)-base.csv'

```



It seems not works for me.
Thus I try another method, and I start basex docker from https://github.com/BaseXdb/, at the same time, I mount my output_database to the docker container.

Can you give me a tutorial about how to translate the Query.xml to basex query sentence!
I will be deeply grateful!

**Comment by rjplevin** [comment]
> Can you give me a tutorial about how to translate the Query.xml to basex query sentence

No, sorry. I have no experience with using BaseX with docker.

> ERROR; java.lang.NoClassDefFoundError: org/basex/core/Proc

This suggests that your class path is incorrect, since the BaseX jar file hasn't been found.

Unfortunately, the configuration of GCAM and pygcam are complex enough that it is virtually impossible to debug remotely based on such limited information. As I suggested earlier, please contact me via email to follow up.
